### ISSUE TITLE
Is it possible to use ScottPlot with Data Binding on plottables?

### ISSUE THREAD

**Issue by eduhza** [swharden/ScottPlot#494] opened 2020-07-28 05:18 UTC
I couldn't find anywhere if it is possible.

I've used Syncfusion SfChart before, and it is possible to bind the the chart with it's series collection, for exemple:
`<chart:SfChart x:Name="SfChart1"  Series="{Binding SeriesCollection}" >`

Thant would be amazing to do something similar with ScottPlot, so whenever I update a plottable, the chart updates.
`<WpfPlot Name="wpfPlot1" Plottables={Binding PlottablesCollection} />`

Also, if there is any material about using ScottPlot with mvvm pattern, I would appreciate.

**Comment by StendProg** [comment] 2020-07-28 14:45
Hi @eduhza 
You asked a very interesting question, but unfortunately the answer to it is: not possible now and very difficult to implement.

It is not that difficult to implement the linking of a plottable collection, but how will you create these series?
Ultimately, I would like to see the binding directly of the data arrays and plottable parameters, something like this:
```xml
<wpfPlot Title={Binding ChartTitle}
                ShowLegend={Binding ShowLegend}>
    <PlottableSignal 
        Data={Binding ys}
        LineWidth={Binding SignalLineWidth}
        MinRenderIndex="100"/>
   <PlottableScatter ....>
</wpfPlot>
```
But implementing this is a huge amount of work, current library architecture don't respects to this. 
Plottable params passed throught constructor. Many bugs are found when trying to change them after creation. 
And many more problems...

It is not so difficult to move away from pure MVVM and manipulate the WPFPlot manually from the ViewModel. Although of course this is not as elegant as the example above.

**Comment by eduhza** [comment] 2020-07-28 16:23
Hi @StendProg 
Thank you for your reply.

I do agree with you that binding directly to the data array would be much more simplier and easier and could solve my goals. 
But, I ask about plottables because when you have an array that changes in a very fast rate, you wouldn't want the chart to update that fast, ie, 1000x/sec, instead of updating everynew element, you can change the whole plottable. 

That's what I've being doing with [Syncfusion SfChart on Xamarin](https://www.syncfusion.com/kb/10702/how-to-bind-series-from-mvvm-pattern-in-xamarin-forms-chart).

`<chart:SfChart Series="{Binding SeriesCollection}"`

The SfChart has its ChartSeriesCollection which I declare my SeriesCollection as a new ChartSeriesCollection with INotifyPropertyChanged. 

```
    private ChartSeriesCollection _seriesCollection;
    public ChartSeriesCollection SeriesCollection 
    { 
        get { return _seriesCollection; } 
        set { SetProperty(ref _seriesCollection, value); }
    }

    public class BaseViewModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        public void OnPropertyChanged([CallerMemberName] string propertyName = "")
        {
            if (PropertyChanged != null)
            {
                PropertyChanged.Invoke(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        protected void SetProperty<T>(ref T backingField, T value, [CallerMemberName] string propertyName = null)
        {
            if (EqualityComparer<T>.Default.Equals(backingField, value)) return;
            backingField = value;
            OnPropertyChanged(propertyName);
        }
    }
```
So first, I create a series and add it to the SeriesCollection. The source of the series is an ObservableCollection of a Class (with X and Y data) that is a CircularBuffer that receives 25 new samples every 25ms.
```
    public ObservableCollection<PlotPageModel> CircularBuffer { get; set; }
    for (int i = 0; i < num; i++)
        {
            CircularBuffer.Add(new PlotPageModel()
             {
                 XData = i.ToString(),
                 YData = rnd.Next(-100, 100)
             });
        }
    SeriesCollection = new ChartSeriesCollection();

    SeriesCollection.Add(UpdatePlotBuffer());

    private FastLineSeries UpdatePlotBuffer()
    {
        ObservableCollection<PlotPageModel> TempData = clone(CircularBuffer); // a function to clone the buffer

        FastLineSeries tempSeries = new FastLineSeries()
        {
             ItemsSource = TempData,
             XBindingPath = "XData",
             YBindingPath = "YData",
             Color = Color.Red,
             EnableAntiAliasing = false,
             EnableTooltip = false,
             ShowTrackballInfo = false,
             StrokeWidth = 1
        };
        return tempSeries;
    }

    public class PlotPageModel
    {
        public string XData { get; set; }
        public int YData { get; set; }
    }
```
If I directly binded the CircularBuffer to the chart, it would update every ms, which may be undesired due to overprocessing.
So, whenever i want to update the graph, I clone the CircularBuffer, create a new FastLineSeries and set SeriesCollection[0] = the new FastLineSeries.

```
    void Update_Graph_Series()
    {
        FastLineSeries newSeries = UpdatePlotBuffer();
    	SeriesCollection[0] = newSeries;
    }
```

The approach you gave does the same, but to a singular Plottable and I'm sure that could be used on the same manner.

Just to clarify my mind on the codings, right now, to use ScottPlot on WPF the propper way is on the code behind?

**Comment by StendProg** [comment] 2020-07-28 17:28
>Just to clarify my mind on the codings, right now, to use ScottPlot on WPF the propper way is on the code behind?

Unfortunately yes.

It looks like your decision is strongly tied to another library, it is more correct for ScottPlot to take a different approach.
Check `GrovingData demo` it's close to your goal.
You can declare large `xs[]` `ys[]` arrays in you `ViewModel`.
Plot single `Plottable` with this arrays passed.
Then data arrived you write it to this arrays, this don't trigger `Render`.
Then you need refresh, you customize the displayed part by using `minRenderIndex` `maxRenderIndex` and trigger `wpfPlot.Render()` manualy whenever you want.
So you dont need to recreate any `Plottable` just setup new boundaries by `minRenderIndex` `maxRenderIndex` or refill whole array, it works fast.

**Comment by eduhza** [comment] 2020-07-28 18:40
Perfect. That's quite similar to WinForms. I've tested here and works.

The last question about this, you said about declaring `xs[]` and `ys[]` in my `ViewModel`, not in my `View.xaml.cs` (code behind).
In my `ViewModel` I'm unnable to interact with `wpfPlot` and it's `Plottable`.

Do you really meant on the `ViewModel`? If so, how can I implement that?
I checked the `GrovingData demo` but I couldn't find it's source code.

Thank you @StendProg

**Comment by StendProg** [comment] 2020-07-28 19:37
> The last question about this, you said about declaring xs[] and ys[] in my ViewModel, not in my View.xaml.cs (code behind).
In my ViewModel I'm unnable to interact with wpfPlot and it's Plottable.

You can create WpfPlot in ViewModel:
```c#
public class SomeViewModel: INotifyPropertyChange
{
    public WPFPlot plotControl {get;set;} 
    public SomeViewModel()
    {
       plotControl = new WPFPlot();
       plotControl.Width = ... // manual setup control
    }
}
```
and bind it in you view:
```xml
<ContentControl Content={Binding plotControl}>
```

It's bad pattern bring control to VM, but it should work.


> I checked the GrovingData demo but I couldn't find it's source code.

https://github.com/swharden/ScottPlot/blob/master/src/ScottPlot.Demo.WPF/WpfDemos/LiveDataGrowing.xaml.cs

**Comment by eduhza** [comment] 2020-07-28 21:06
Ok @StendProg 

I'll make some tests. Later I can comment about my findings.

Thank you.

**Comment by swharden** [comment] 2020-08-09 22:32
Hey @eduhza, thanks for raising this issue, and @StendProg for your insightful comments along the way.

@StendProg described the state of ScottPlot very well, and I'll just add a couple comments for additional context. 

MVVM pattern is very common in the .NET word (and is used by many .NET charting libraries, especially for WPF) but ScottPlot's API was designed to mimic that of [matplotlib (a very popular charting library for Python)](https://matplotlib.org/) which uses sequential method calls to load data with numerous optional arguments for style customization.

ScottPlot was designed to make it as easy as possible to create plots from console applications (with WinForms and WPF controls provided as lite wrappers to provide interactivity in GUI environments). As @StendProg noted, adapting it to fit MVVM would be pretty difficult to do well. The best way to go, for now, is for the programmer to control data updates and rendering manually.

@eduhza if you have more questions along the way let us know! Similarly, if your tests reveal interesting findings feel free to share them here. I'll close this issue for now, but thanks again for opening it initially.

**Closed by swharden** 2020-08-09 22:32 UTC
Labels: Question
