### ISSUE TITLE
How do I match xs with ys in SignalPlot

### ISSUE THREAD

**Issue by shaymongracia** [swharden/ScottPlot#368] opened 2020-05-02 21:55 UTC
Hi Scott,

I have a question, how do I match the xs with ys in the SignalPlot? I mean, I'm trying to logging a signal is coming from current shunt resistor but I need the x axis as timespan, is this possible?

Regards

**Comment by swharden** [comment] 2020-05-02 23:28
Hi @shaymongracia, 

You can define limits manually

```cs
plt.Axis(x1, x2, y1, y2)
```

or automatically

```cs
plt.AxisAuto()
```

If you do this in a user controls be sure to redraw the image after adjusting the axis:
```
formsPlot1.Render()
```

Does this fully answer your question?

**Comment by swharden** [comment] 2020-05-02 23:30
... if you're asking about how to set the sample rate and horizontal offset of a signal plot, check the SignalPlot() arguments.

http://swharden.com/scottplot/cookbooks/4.0.29/#customize-ticks-datetime-axis

Does this answer your question?

**Comment by shaymongracia** [comment] 2020-05-03 17:30
Hi Scott,

Probably I didn't explain well what I mean. I want to plot a signal values based on time where each value was read. I did a example code below, what I found is the coordinate point match well in "y" axis but not in the "x" axis, instead in "x" axis match with the array index.

For instance 
YVALUES[2] = 1.593 <= this value supposed to comes from sensor reading.
XVALUES[2] = 59.843 <= this value is took from Stopwatch.ElapsedMilliseconds

When I look into coordinate point in the plot is y=1.593 and x=2, coordinate point on "x" is based on the array index instead of time based.

I didn't found the way to match the coordinate point with time.

`public partial class MainWindow : Window
    {
        /// <summary>
        /// Represent the max array size, also used to recerve memory to store dumy (0) data.
        /// </summary>
        private const int DATA_LENGTH = 1_000_000;

        /// <summary>
        /// UI Render rate.
        /// </summary>
        private const int REFRESHRATE = 10;

        /// <summary>
        /// Represent the max "x" values to be displayed.
        /// </summary>
        private int XMAXRENDERINDEX = 10;

        /// <summary>
        /// Represent the max "y" values to be displayed.
        /// </summary>
        private int YMAXRENDERINDEX = 50;

        /// <summary>
        /// Sample rate of the data. To be use when time scale needs to be changed from milli seconds to seconds, minutes, hours, days, etc.
        /// </summary>
        private int SAMPLERATE = 1000;

        /// <summary>
        /// To store the current index of the data.
        /// </summary>
        private int DATAINDEX = 0;

        /// <summary>
        /// Y series data, values represents current (I) in milli amperes.
        /// </summary>
        private double[] YVALUES = new double[DATA_LENGTH];

        /// <summary>
        /// X series data, values represents time in milli seconds.
        /// </summary>
        private double[] XVALUES = new double[DATA_LENGTH];

        private double[] DUMYVALUES = DataGen.RandomWalk(new Random(0), DATA_LENGTH);

        /// <summary>
        /// To store the Signal Plot object to use in different part of the project.
        /// </summary>
        private PlottableSignal SIGNALPLOT;

        /// <summary>
        /// To generate random value, just for testing. Real values will come from sensor thru serial COM port.
        /// </summary>
        private Random RAND = new Random(0);

        /// <summary>
        /// To mesure time elapsed between each YVALUES data array.
        /// </summary>
        private Stopwatch STOPWATCH = new Stopwatch();

        public MainWindow()
        {
            InitializeComponent();

            var t = mainPlt.plt.GetSettings();

            // Initialize the SignalPlot object. Sample rate = 1000
            SIGNALPLOT = mainPlt.plt.PlotSignal(ys: YVALUES, sampleRate: SAMPLERATE, color: Color.White, lineWidth: .5, markerSize: 5f, maxRenderIndex: DATAINDEX, label: "Current (I)");

            mainPlt.plt.YLabel("Current (mA)");
            mainPlt.plt.XLabel("Time (ms)");

            mainPlt.plt.Style(ScottPlot.Style.Black);
            mainPlt.plt.Axis(0, XMAXRENDERINDEX, 0, YMAXRENDERINDEX);
            mainPlt.plt.Legend();
            

            mainPlt.plt.Ticks(rulerModeY: true);


            DispatcherTimer updateDataTimer = new DispatcherTimer();
            updateDataTimer.Interval = TimeSpan.FromMilliseconds(1);
            updateDataTimer.Tick += UpdateDataFromDumy;
            updateDataTimer.Start();


            DispatcherTimer renderTimer = new DispatcherTimer();
            renderTimer.Interval = TimeSpan.FromMilliseconds(REFRESHRATE);
            renderTimer.Tick += Render;
            renderTimer.Start();
        }

        void UpdateDataFromDumy(object sender, EventArgs e)
        {
            if (DATAINDEX == 0)
                STOPWATCH.Start();

            XVALUES[DATAINDEX] = STOPWATCH.ElapsedMilliseconds;
            YVALUES[DATAINDEX] = DUMYVALUES[DATAINDEX];
            
            SIGNALPLOT.maxRenderIndex = DATAINDEX;

            DATAINDEX += 1;
        }

        void Render(object sender, EventArgs e)
        {
            mainPlt.Render(skipIfCurrentlyRendering: true);
        }
    }`

**Comment by swharden** [comment] 2020-05-03 17:55
Hi @shaymongracia,

You are displaying data as a signal plot:

```cs
SIGNALPLOT = mainPlt.plt.PlotSignal(YVALUES, SAMPLERATE);
```

The problem is that signal plots can only plot evenly-spaced data. Your data is not evenly spaced. Your horizontal values are stored in `XVALUES`. However, your code currently does not use `XVALUES` at all.

Instead, use a scatter plot:
```cs
mainPlt.plt.PlotScatter(XVALUES, YVALUES);
```

Does this solve your problem?

**Comment by swharden** [comment] 2020-05-03 21:16
I'll close this issue for now, but feel free to open it again if I didn't properly understand your question 👍

**Closed by swharden** 2020-05-03 21:16 UTC
Labels: Question
