### ISSUE TITLE
Polygon is a slight bit shorter than a signal-line

### ISSUE THREAD

**Issue by SeidChr** [swharden/ScottPlot#342] opened 2020-04-10 11:28 UTC
**Describe the bug**
when drawing a signal on the top line of a polygon, the signal is just a tiny bit longer than the polygon is wide, even when using the exact same values on the x axis.
(please verify this, because the signal tics is calculated in scottplot, and the polygon tics are calculated manually (+1d))

**To Reproduce**
draw a signal on the top line of an polygon

How i increment the tics: https://github.com/SeidChr/COVID-19-Report-Data-Pipeline/blob/310f4e91988ad31519bc951396795f249db5db61/src/Plotting/Plotter.cs#L443

**Screenshots**
![image](https://user-images.githubusercontent.com/1927076/78987530-8f3be280-7b2e-11ea-8f71-8b2d5afed6e6.png)

**Comment by swharden** [comment] 2020-04-11 00:08
Hey @SeidChr, thanks for reporting this! I got thrown off by this one...

## First thought (System.Drawing)
* perhaps lines and polygon fills don't match perfectly
* perhaps the "cap" on lines (which is a thing, and could be disabled) makes them hang over

I tested this by adding a test that exclusively uses System.Drawing to draw a line on the edge of a polygon. To my surprise, it works perfectly, so this issue is indeed a ScottPlot issue...

```cs
var bmp = new System.Drawing.Bitmap(320, 240);

using (var pen = new Pen(Color.Blue, 2))
using (var brush = new SolidBrush(Color.LightGreen))
using (var gfx = Graphics.FromImage(bmp))
{
	gfx.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.AntiAlias;
	gfx.Clear(Color.White);

	Point[] points = {
		new Point(75, 100),
		new Point(250, 75),
		new Point(280, 200),
		new Point(100, 220)
	};

	gfx.FillPolygon(brush, points);
	gfx.DrawLine(pen, points[0], points[1]);
}
```

![image](https://user-images.githubusercontent.com/4165489/79029784-ea3bfc80-7b63-11ea-881c-968feb930678.png)
![image](https://user-images.githubusercontent.com/4165489/79029800-f9bb4580-7b63-11ea-879a-9979b91a1049.png)

## Second thought (signal vs. scatter)
Signal plot is designed to plot millions of points in real time. To display data at such high speed it uses some math shortcuts, and it would not surprise me if it were off by 1 pixel. I'm curious if it's shifted right one pixel on all corners (correctable with a 1px shift everywhere) or if it's shifted "wide" on the left and white. I wrote a test to investigate.

```cs
double[] xs = { 75, 250, 280, 100 };
double[] ys = { -100, -75, -200, -220 };

var plt = new ScottPlot.Plot(320, 240);
plt.PlotPolygon(xs, ys, fillColor: Color.LightGreen);
plt.PlotLine(xs[0], ys[0], xs[1], ys[1], Color.Blue);
plt.Grid(false);
plt.Frame(false);
plt.Ticks(false, false);
plt.Title("Line/Scatter");
```

![image](https://user-images.githubusercontent.com/4165489/79030102-74d12b80-7b65-11ea-8c92-90a7f420439a.png)
![image](https://user-images.githubusercontent.com/4165489/79030109-7dc1fd00-7b65-11ea-8ddc-ef4e392fff04.png)

```cs
double[] xs = { 75, 250, 280, 100 };
double[] ys = { -100, -75, -200, -220 };

var plt = new ScottPlot.Plot(320, 240);
plt.PlotPolygon(xs, ys, fillColor: Color.LightGreen);
plt.PlotSignal(
	ys: new double[] { ys[0], ys[1] },
	sampleRate: 1.0 / (xs[1] - xs[0]),
	xOffset: xs[0],
	color: Color.Blue,
	markerSize: 0
	);
plt.Grid(false);
plt.Frame(false);
plt.Ticks(false, false);
plt.Title("Signal");
```

![image](https://user-images.githubusercontent.com/4165489/79030225-06d93400-7b66-11ea-804e-e582cd919dcd.png)
![image](https://user-images.githubusercontent.com/4165489/79030219-017be980-7b66-11ea-8a63-ce12ee4fbde0.png)

## Current thinking
On my end I can't demonstrate any misalignment of signal, scatter, or polygon plots. 

* Could you send a ~10 line example that demonstrates this bug? Your sample code is pretty intense (almost 500 lines!) and there's a lot going on in there. I tagged some recent commits to this issue you can look at for reference.

* Perhaps double-check your source data and confirm the values you're sending the polygon are truly identical to the values you're sending the Signal

* It would also be helpful to know if this bug affects all corners, or just the top right. Having a ~10 line test that demonstrates this and lets us investigate this closer could help answer this.

Since I can't reproduce this on my end I'll close the issue for now, but feel free to open it again if you come up with a simple standalone test/demo of this error. Thanks again for your feedback!

**Closed by swharden** 2020-04-11 00:08 UTC
Labels: BUG

**Comment by SeidChr** [comment] 2020-04-11 08:47
I actually can see it in all of your screenshots 😅 
its not as extreme as on my sample though.

it took it to the gimp, but its still a tough thing to see due to the gradient
![image](https://user-images.githubusercontent.com/1927076v/79039363-05991d00-7be1-11ea-88f1-2bba2299095e.png)

seems like i have to debug this

**Comment by SeidChr** [comment] 2020-04-11 09:18
calculation of the day tics xs seems to be fine
![image](https://user-images.githubusercontent.com/1927076/79039948-28c5cb80-7be5-11ea-8a9e-745fc1831752.png)
debugging the start i pass into PlotSignal: 43852 
+79 gives the 43931

are you doing any dividing on the sampleRate calculation?
might be some rounding issue on the higher scales

**Comment by SeidChr** [comment] 2020-04-11 10:12
Ok, i tried replacing PlotSignal by PlotScatter, which indeed shows the exact same behavior.
Then i realized, that the first point of the scatter also does not draw directly ON the tic line, but starts right of it. So i thought, somewhere in the calculation everything is shifted just a little bit.

In the end I worked around this now, by shifting all y-tics to the left by 0.05, which gives a good result.
It still does start right of the very first tic line 😅 (but that doesn't matter to me)

I was unable to figure out the "dotnet test" behaviour to setup a text project for this, but i think the error may show up more if you use really high values for x. eg draw a line from 1000000 to 1000005.
Since my diagramm is in the 50k range with a visible error, and yours is in the 1k range with almost invisible error, i assume the absolute value of y seems to be relevant.

**Comment by swharden** [comment] 2020-04-11 14:11
I'm glad to hear you solved this issue - your new plot looks great!

> the error may show up more if you use really high values for x. eg draw a line from 1000000 to 1000005.

I'll make a new test case for this and post the results here shortly. Thanks for the suggestion!

> I was unable to figure out the "dotnet test" behavior to setup a test project for this

If you haven't used tests in visual studio before, I recommend checking it out. Show the test explorer (view -> test explorer), then just right-click a test, hit run, and view the output. 

This is definitely a faster workflow than developing by modifying your main function, hitting F5, launching your whole application in a debugger, and interacting with it just to view the output of a small piece of code. 👍 

![image](https://user-images.githubusercontent.com/4165489/79045994-1d21d700-7bdc-11ea-8ea6-a6597c399f0e.png)

**Comment by swharden** [comment] 2020-04-11 14:16
> > the error may show up more if you use really high values for x. eg draw a line from 1000000 to 1000005.
> 
> I'll make a new test case for this and post the results here shortly. Thanks for the suggestion!

The output is identical actually! This is a good sign that ScottPlot is producing the desired output even when large numbers are used.

```cs
double[] xs = { 1e6 + 75, 1e6 + 250, 1e6 + 280, 1e6 + 100 };
double[] ys = { 1e6 - 100, 1e6 - 75, 1e6 - 200, 1e6 - 220 };

var plt = new ScottPlot.Plot(320, 240);
plt.PlotPolygon(xs, ys, fillColor: Color.LightGreen);
plt.PlotSignal(
	ys: new double[] { ys[0], ys[1] },
	sampleRate: 1.0 / (xs[1] - xs[0]),
	xOffset: xs[0],
	color: Color.Blue,
	markerSize: 0
	);
plt.Grid(false);
plt.Frame(false);
plt.Ticks(false, false);
plt.Title("Large Value Signal");
```

![image](https://user-images.githubusercontent.com/4165489/79046154-34ad8f80-7bdd-11ea-8d27-4ab05d4629df.png)
