### ISSUE TITLE
Console application freezes while creating new instance of a ScottPlot.Plot

### ISSUE THREAD

**Issue by DenisBelobrotski** [swharden/ScottPlot#661] opened 2020-12-17 08:10 UTC
Application just freezes while creating new instance of Plot.
It is possible to reproduce the issue with JetBrains Rider 2020.2 on MacOS v.10.15.4 with ScottPlot v.4.0.47 and System.Drawing.Common v.4.7.0.
On Windows 10 with same IDE and packages it works fine and correctly.

Test application source
```cs
using ScottPlot;

namespace ScottPlotTest
{
   class Program
   {
      public static void Main(string[] args)
      {
         Plot plot = new Plot();
      }
   }
}
```

**Comment by swharden** [comment] 2020-12-20 02:39
Hi @DenisBelobrotski, this is a new one for me! I'm happy to help troubleshoot this but I don't have a MacOS computer, and this project passes building and running tests on MacOS in Azure Pipelines so this seems like a MacOS/version-specific issue of some sort...

Are you able to create a basic drawing in a new console application with just the `System.Drawing.Common` NuGet package? You may need to install the `runtime.osx.10.10-x64.CoreCompat.System.Drawing` package.

```cs
using System;
using System.Drawing;

namespace ConsoleApp9
{
    class Program
    {
        static void Main(string[] args)
        {
            var bmp = new Bitmap(400, 300);
            using(var gfx = Graphics.FromImage(bmp))
            {
                gfx.Clear(Color.Navy);
                gfx.DrawLine(Pens.Yellow, 10, 20, 100, 200);
            }
            bmp.Save("test.bmp");
        }
    }
}
```

If this code fails, the issue is probably related to System.Drawing.Common (not ScottPlot).

I'll close this issue for now, but feel free to share your findings and we can open it up again if it looks like there's something we can do to improve ScottPlot. This might be a hard one since I don't have a mac and ScottPlot builds/tests fine on Azure Pipelines' MacOS servers 😅

**Closed by swharden** 2020-12-20 02:39 UTC
Labels: BUG

**Comment by DenisBelobrotski** [comment] 2020-12-20 07:56
Hi, @swharden, thanks for your response. You're absolutely right, it's some issue with `System.Drawing.Common` :). 

Could you please share with me characteristics of your Azure Pipelines MacOS machine and project on it if it's possible. It would be very helpful for me, because I really interested in understanding where the problem is (MacOS version, JetBrains IDE, `System.Drawing.Common` version or something else).

**Comment by swharden** [comment] 2020-12-20 16:20
### System.Drawing on MacOS in the Cloud (Azure Pipelines)

I don't know much about the hardware. I use Azure Pipelines to build and test this code (in the cloud using Microsoft's computers) any time a commit is made and uploaded. I define the cloud build/test OS here:

https://github.com/swharden/ScottPlot/blob/5cbf9262001a539c34bb9a5b9aca691b5ef483a7/dev/devops/azure-pipelines.yml#L11-L13

And `macOS-latest` is described here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software so I'm guessing it's `macOS X Catalina 10.15`? Not sure how different that is from what you're running.

### System.Drawing on MacOS Locally

According to https://github.com/corecompat/corecompat#running-systemdrawing-for-net-core-on-os-x-or-linux "On Linux and macOS, you need to install libgdiplus." and "For example, on macOS, run `brew install mono-libgdiplus`"

Does this help?
