### ISSUE TITLE
Strip Chart Demo

### ISSUE THREAD

**Issue by AteCoder** [swharden/ScottPlot#540] opened 2020-09-11 00:32 UTC
**Describe the bug**
It seems the plot.Clear() does not remove a previously plotted PlotSignal 

**To Reproduce**
(1) Use plt.PlotSignal to plot a signal.
(2) on the same form, use plt.Clear() to clear all Plottables.
(3) add plot.Scatter
(4) render the form
(5) plot seems to switch between the Signal and Scatter plots.

The code below shows how the signal can be removed.  However, I thought .Clear() should have done that. 
.Clear(Of  did not seem to remove the signal either. 

```vb.net
       With Me._ScottPlot.plt
            .Clear()
            Me._Signal = .PlotSignal(Me.OrdinateValues, Me.SamplingRate, markerSize:=0)
            .Title("'Sampled' Sine Wave")
            .YLabel("wave")
            .XLabel("Seconds")
            .Grid(Me._GridCheckBox.Checked)
            .AxisAuto(0)
        End With

        With Me._ScottPlot.plt
            .Clear()
            If Me.Signal IsNot Nothing Then .Remove(Signal)
            .PlotScatter(Me.AbscissaValues, Me.OrdinateValues)
            .PlotScatter(Me.AbscissaValues, Me.OrdinateCosineValues)
            .Title("Sine Wave Phase fixed size")
            .YLabel("signals")
            .XLabel("phase")
            .AxisAuto(0)
        End With

```

**Screenshots**
If applicable, add screenshots to help explain your problem

**Comment by StendProg** [comment] 2020-09-11 14:56
Hi @AteCoder, 
`Clear()` code pretty simple, i double check it. Tried to reproduce your steps in (c#) and it work fine.
Unfortunately, I am not familiar with WB and cannot fully understand the code that you presented.

I can make 2 assumptions:
1. You use old version of `ScottPlot`.
2. VB making the wrong call somehow. There is about 5 overloaded Clear() methods, one of them marked as `[Obsolete]`. Perhaps the VB has its own vision for all this.

If this is possible could you please provide a c # example that reproduces this bug. I have zero experience with VB and I'm afraid otherwise I won't be able to help.

**Comment by AteCoder** [comment] 2020-09-11 18:15
Hi @StendProg

I am using the latest release (4.0.39) from GitHub (source code compiled on my machine) and am able to reproduce this with C#. Note that this is intermittent.

I attached the C# control.  It depends on some other projects.  However, with a bit of effort you can inherit form a user control and remove the electrocardiogram stuff.  Let me know if you’d like me to do this and get you a project with less carry over.

Also attached is a display for the scatter plot when it is stopped showing the image from the electrocardiogram in place of the sine way.

Note that this might be happening because both Signal Plot and Scatter Plot use the same array as I was unable to reproduce this when using a different array for the scatter plot.

Still, I thought it might be pointing to some issue with Scott Plot that you might wish to unearth.

Also note that I was able to see this even if the timer is stopped when switching from the signal plot to the scatter plot.

**Comment by swharden** [comment] 2020-09-11 18:33
Hi @AteCoder 

This topic is being discussed on this page:
https://github.com/swharden/ScottPlot/issues/540

Unfortunately email attachments are not included with your message, but if you go to that URL and make a comment you can drag/drop files into the comment (or copy/paste code as text).

I'm interested in learning more about this!

**Comment by StendProg** [comment] 2020-09-11 18:41
It may well be that a @AteCoder  does not want to make his project accessible to absolutely everyone. Just mail directly to @swharden or/and me (stendgit@gmail.com) if i guess right.

**Comment by AteCoder** [comment] 2020-09-11 20:42
Will do. I will share the entire project tomorrow.
________________________________

**Comment by AteCoder** [comment] 2020-09-12 15:01
I pushed the latest changed to my fork of Scott Plot at:

https://www.bitbucket.org/davidhary/vs.scott.plot

The strip chart VB and C# projects are under Applications\Strip.Charts.

**Comment by StendProg** [comment] 2020-09-12 18:08
Hi @AteCoder,
I get your code, but unfortunately i get about 150 compile errors. There is a lot of references on the missing library. If you know an easy way to isolate the `ScottPlotStripView` into a separate project compiled without `Core`, I would delegate it to you, understanding such a serious project will take a lot of time for me or maybe it's not worth it.

Anyway i check `ScotPlotStripView` code and can get some assumpions.
You are actively using timers, and it is quite possible that `Clear` call is at the time of `Rendering`. `Render` enumerate PlottableList and block its `Clear`.... These are standard multi-threaded problems, so you need to be very careful about timers.

`Dispose` `RefreshTimer` at begining of `InitializeEcgPlot()` and `InitializeSingleSineWavePlot` the same like you done for `SamplingTimer`.
`InitializeSineCosinePhasePlot` seems to be correctly unsubscribing/subscribing. 
It would be logical to define and use the same method for updating timers in all three methods.
Even if you unsubcribe correctly or destroy the timer, then the last rendering may still come to `Clear` call time. To check this assumption try to temponary add some delay before `Clear` call, say 500-1000 ms.

These are all assumptions without a working project in hand, maybe I'm wrong about blocking the `List.Clear()`, in any case, you must correctly delete old timers before creating new ones.
The first thing I would do with working project is put a breakpoint on `Clear ()` call and look at the `plt.settings.Plottables` before and after  `Clear()` call. Maybe you will do it yourself instead of isolating you project. The only thing under the debugger you can see is that everything works fine, in contrast to running without debugging.

Please note how `plot.Clear` works. It just clear internal `plot.settings.Plottables` list. It doesn't remove any plottables, just remove them from this list. So `PlottableSignal` stay in `this.Signal` after `Clear.Call()`. Until you overwrite him with a new one, and then he will live in memory for some time until `Garbage collector` finishes him.

**Comment by AteCoder** [comment] 2020-09-12 18:57
Thank you for taking a look at the code and for your suggestions.

Indeed, seeing that this was intermittent, I tend to agree that this most likely is a multi-threading issue. Seeing that this was a minor demo project just to see how I can best strip chart, I was not particularly concerned about the multi-threading implications of the timer.

The take home less though is clearly in your last comments. Obviously, plottables must be disposed for this code to work correctly.

Still, I will make the changes you suggested and watch for the consequences just in case there still is something that might be affecting how the plot is rendered and keep you posted.

Thanks again for your great effort.  Must appreciated.  Looking forward for Scott Plot 5.

**Comment by AteCoder** [comment] 2020-09-13 16:45
Done.  Indeed, it seems properly handling the timers fixed that issue.

My forked project now includes only the Scott Plot project. You are welcome to incorporate the strip charts if you find value in those.

Thanks you

David

**Comment by swharden** [comment] 2020-09-13 18:21
@StendProg thank you for your extensive answers and initial review of this code! 

@AteCoder, it's a bit intimidating and time consuming to review a whole new code base, however I found your demo program and compiled it easily (thanks for removing those dependencies) and it looks like you've mostly figured this out by now. 

![ecg](https://user-images.githubusercontent.com/4165489/93025375-734fd780-f5cb-11ea-8036-6441be9ea04c.gif)

I think it would be a good idea for me to add a strip chart demo to the ScottPlot demo collection to make it easier for others to discover how to do this in the future. I'll mimic your ECG demo, which is a personal interest of mine since I have used ScottPlot to display a real ECG in the past (https://github.com/swharden/SoundCardECG).

The Electrocardiogram module in your code base is MIT licensed which makes it very useful and easy to include into the ScottPlot demo: https://bitbucket.org/davidhary/vs.scott.plot/src/master/Applications/Strip.Charts/Platform/Electrocardiogram.cs

**Comment by AteCoder** [comment] 2020-09-13 18:26
It is all a remix; we r just standing on the shoulders of giants.

Hear! Hear! U made my day.

The source points to where I got the simulated code. It took some fiddling and cleanup; a remix.
________________________________

**Comment by swharden** [comment] 2020-09-13 19:03
I just remembered that I made something similar before. You may be interested to see https://github.com/swharden/HHSharp

![screenshot-sEPSCs](https://user-images.githubusercontent.com/4165489/93026193-389d6d80-f5d2-11ea-8d81-9bc1d382e747.gif)

**Comment by swharden** [comment] 2020-09-13 19:14
Instead of making a separate strip chart demo, I just updated the WinForms "live data" demo to show an ECG. There is an option to switch between "roll" and "scroll" behavior. I'll do the same for the WPF demo.

Note that there are two timers: one for updating the simulated data, and a separate timer for rendering. This way slowness of one process will not affect the other 👍 

![ecg2](https://user-images.githubusercontent.com/4165489/93026303-1a843d00-f5d3-11ea-98d0-3af6adf4eaf8.gif)

![ecg3](https://user-images.githubusercontent.com/4165489/93026305-1a843d00-f5d3-11ea-9d60-740ec83b9c37.gif)

**Closed** 2020-09-13 19:30 UTC
Labels: BUG
